AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Documentation:
  Enabled: false
