AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false
