# frozen_string_literal: true

RSpec.describe Gotsha::ActionDispatcher do
  describe "without any action name" do
    it "calls Run action" do
      expect_any_instance_of(Gotsha::Actions::Run).to receive(:call)

      described_class.call
    end
  end

  describe "with unknown action name" do
    let(:unknown_action) { "obey" }

    it "raises HardFail error with user friendly message" do
      expect do
        described_class.call(unknown_action)
      end.to raise_error(Gotsha::Errors::HardFail)
    end
  end

  describe "with a valid action" do
    let(:action) { "init" }

    it "calls the action" do
      expect_any_instance_of(Gotsha::Actions::Init).to receive(:call)

      described_class.call(action)
    end
  end

  context "with autogenerated config" do
    before do
      allow(Gotsha::Config::USER_CONFIG)
        .to receive(:key?)
        .with("autogenerated")
        .and_return(true)
    end

    it "fails with proper error" do
      expect do
        described_class.call
      end.to raise_exception(
        Gotsha::Errors::HardFail,
        "autogenerated config detected! Please, remove `autogenerated: true` from `.gotsha/config.yml`"
      )
    end
  end
end
