# frozen_string_literal: true

RSpec.describe Gotsha::ActionDispatcher do
  describe "without any action name" do
    it "calls Run action" do
      expect_any_instance_of(Gotsha::Actions::Run).to receive(:call)

      described_class.call
    end
  end

  describe "with unknown action name" do
    let(:unknown_action) { "obey" }

    it "raises HardFail error with user friendly message" do
      expect do
        described_class.call(unknown_action)
      end.to raise_error(Gotsha::Errors::HardFail)
    end
  end

  describe "with a valid action" do
    let(:action) { "init" }

    it "calls the action" do
      expect_any_instance_of(Gotsha::Actions::Init).to receive(:call)

      described_class.call(action)
    end
  end

  describe "with autogenerated config" do
    before do
      allow(Gotsha::UserConfig)
        .to receive(:get)
        .and_return(true)
    end

    it "fails with proper error" do
      expect do
        described_class.call
      end.to raise_exception(
        Gotsha::Errors::HardFail,
        "autogenerated config detected! Please, remove `autogenerated = true` from `.gotsha/config.toml`"
      )
    end
  end

  describe "with no config" do
    before do
      allow(Gotsha::UserConfig)
        .to receive(:blank?)
        .and_return(true)
    end

    context "with other action than `init`" do
      it "fails with proper error" do
        expect do
          described_class.call
        end.to raise_exception(
          Gotsha::Errors::HardFail,
          "config files not found, please run `bundle exec gotsha init` first"
        )
      end
    end

    context "with `init` action" do
      it "calls the action witohut exception" do
        expect_any_instance_of(Gotsha::Actions::Init).to receive(:call)

        described_class.call(:init)
      end
    end
  end
end
