name: Gotsha

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install Gotsha
        run: gem install gotsha

      - name: Fetch Gotsha notes
        run: git fetch origin 'refs/notes/gotsha:refs/notes/gotsha'

      - name: Show tests output
        run: GOTSHA_CI=1 gotsha show
