# .github/workflows/macos.yml
name: macOS Ruby CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.3']
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Build & smoke-test the gem
        run: |
          gem install gotsha rubocop rspec
          GOTSHA_VERBOSE=1 gotsha init
          GOTSHA_VERBOSE=1 gotsha test
          GOTSHA_VERBOSE=1 gotsha show

