# .github/workflows/macos.yml
name: macOS Ruby CI

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.3']
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install Git
        run: brew install git

      - name: Build & smoke-test the gem
        run: |
          git -v
          gem install gotsha
          GOTSBA_CI=1 GOTSHA_VERBOSE=1 gotsha init
          GOTSHA_CI=1 GOTSHA_VERBOSE=1 gotsha help
          GOTSHA_CI=1 GOTSHA_VERBOSE=1 gotsha

