# .github/workflows/macos.yml
name: MacOS smoke-test

on:
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby: ['3.3']
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install gems
        run: |
          gem install gotsha rubocop rspec

      - name: Init & run Gotsha
        run: |
          GOTSHA_VERBOSE=1 gotsha init
          GOTSHA_VERBOSE=1 gotsha test || true
          GOTSHA_VERBOSE=1 gotsha show || true

